package com.edu.unbosque.tiendaonline.entidad;
// Generated 24/11/2015 08:30:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer idenCategoria;
     private String nombCategoria;
     private String descCategoria;
     private Set subcategorias = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String nombCategoria, String descCategoria) {
        this.nombCategoria = nombCategoria;
        this.descCategoria = descCategoria;
    }
    public Categoria(String nombCategoria, String descCategoria, Set subcategorias) {
       this.nombCategoria = nombCategoria;
       this.descCategoria = descCategoria;
       this.subcategorias = subcategorias;
    }
   
    public Integer getIdenCategoria() {
        return this.idenCategoria;
    }
    
    public void setIdenCategoria(Integer idenCategoria) {
        this.idenCategoria = idenCategoria;
    }
    public String getNombCategoria() {
        return this.nombCategoria;
    }
    
    public void setNombCategoria(String nombCategoria) {
        this.nombCategoria = nombCategoria;
    }
    public String getDescCategoria() {
        return this.descCategoria;
    }
    
    public void setDescCategoria(String descCategoria) {
        this.descCategoria = descCategoria;
    }
    public Set getSubcategorias() {
        return this.subcategorias;
    }
    
    public void setSubcategorias(Set subcategorias) {
        this.subcategorias = subcategorias;
    }




}


