package com.edu.unbosque.tiendaonline.entidad;
// Generated 24/11/2015 08:30:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Entregacosto generated by hbm2java
 */
public class Entregacosto  implements java.io.Serializable {


     private Integer idenEntregaCosto;
     private String nombZonaEntregaCosto;
     private double costoEntregaCosto;
     private Set ordenproductos = new HashSet(0);

    public Entregacosto() {
    }

	
    public Entregacosto(String nombZonaEntregaCosto, double costoEntregaCosto) {
        this.nombZonaEntregaCosto = nombZonaEntregaCosto;
        this.costoEntregaCosto = costoEntregaCosto;
    }
    public Entregacosto(String nombZonaEntregaCosto, double costoEntregaCosto, Set ordenproductos) {
       this.nombZonaEntregaCosto = nombZonaEntregaCosto;
       this.costoEntregaCosto = costoEntregaCosto;
       this.ordenproductos = ordenproductos;
    }
   
    public Integer getIdenEntregaCosto() {
        return this.idenEntregaCosto;
    }
    
    public void setIdenEntregaCosto(Integer idenEntregaCosto) {
        this.idenEntregaCosto = idenEntregaCosto;
    }
    public String getNombZonaEntregaCosto() {
        return this.nombZonaEntregaCosto;
    }
    
    public void setNombZonaEntregaCosto(String nombZonaEntregaCosto) {
        this.nombZonaEntregaCosto = nombZonaEntregaCosto;
    }
    public double getCostoEntregaCosto() {
        return this.costoEntregaCosto;
    }
    
    public void setCostoEntregaCosto(double costoEntregaCosto) {
        this.costoEntregaCosto = costoEntregaCosto;
    }
    public Set getOrdenproductos() {
        return this.ordenproductos;
    }
    
    public void setOrdenproductos(Set ordenproductos) {
        this.ordenproductos = ordenproductos;
    }




}


