package com.edu.unbosque.tiendaonline.entidad;
// Generated 24/11/2015 08:30:01 PM by Hibernate Tools 4.3.1



/**
 * Ordenproductodetalle generated by hbm2java
 */
public class Ordenproductodetalle  implements java.io.Serializable {


     private Integer idenOrdenProductoDetalle;
     private Ordenproducto ordenproducto;
     private Producto producto;
     private int cantOrdenProductoDetalle;

    public Ordenproductodetalle() {
    }

    public Ordenproductodetalle(Ordenproducto ordenproducto, Producto producto, int cantOrdenProductoDetalle) {
       this.ordenproducto = ordenproducto;
       this.producto = producto;
       this.cantOrdenProductoDetalle = cantOrdenProductoDetalle;
    }
   
    public Integer getIdenOrdenProductoDetalle() {
        return this.idenOrdenProductoDetalle;
    }
    
    public void setIdenOrdenProductoDetalle(Integer idenOrdenProductoDetalle) {
        this.idenOrdenProductoDetalle = idenOrdenProductoDetalle;
    }
    public Ordenproducto getOrdenproducto() {
        return this.ordenproducto;
    }
    
    public void setOrdenproducto(Ordenproducto ordenproducto) {
        this.ordenproducto = ordenproducto;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantOrdenProductoDetalle() {
        return this.cantOrdenProductoDetalle;
    }
    
    public void setCantOrdenProductoDetalle(int cantOrdenProductoDetalle) {
        this.cantOrdenProductoDetalle = cantOrdenProductoDetalle;
    }




}


