package com.edu.unbosque.tiendaonline.entidad;
// Generated 24/11/2015 08:30:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ordenproducto generated by hbm2java
 */
public class Ordenproducto  implements java.io.Serializable {


     private Integer idenOrdenProducto;
     private Entregacosto entregacosto;
     private Usuario usuario;
     private int idenProdOrdenProducto;
     private Date fechOrdenProducto;
     private int cantOrdenProducto;
     private double precOrdenProducto;
     private String statusOrdenProducto;
     private Set ordenproductodetalles = new HashSet(0);

    public Ordenproducto() {
    }

	
    public Ordenproducto(Entregacosto entregacosto, Usuario usuario, int idenProdOrdenProducto, Date fechOrdenProducto, int cantOrdenProducto, double precOrdenProducto, String statusOrdenProducto) {
        this.entregacosto = entregacosto;
        this.usuario = usuario;
        this.idenProdOrdenProducto = idenProdOrdenProducto;
        this.fechOrdenProducto = fechOrdenProducto;
        this.cantOrdenProducto = cantOrdenProducto;
        this.precOrdenProducto = precOrdenProducto;
        this.statusOrdenProducto = statusOrdenProducto;
    }
    public Ordenproducto(Entregacosto entregacosto, Usuario usuario, int idenProdOrdenProducto, Date fechOrdenProducto, int cantOrdenProducto, double precOrdenProducto, String statusOrdenProducto, Set ordenproductodetalles) {
       this.entregacosto = entregacosto;
       this.usuario = usuario;
       this.idenProdOrdenProducto = idenProdOrdenProducto;
       this.fechOrdenProducto = fechOrdenProducto;
       this.cantOrdenProducto = cantOrdenProducto;
       this.precOrdenProducto = precOrdenProducto;
       this.statusOrdenProducto = statusOrdenProducto;
       this.ordenproductodetalles = ordenproductodetalles;
    }
   
    public Integer getIdenOrdenProducto() {
        return this.idenOrdenProducto;
    }
    
    public void setIdenOrdenProducto(Integer idenOrdenProducto) {
        this.idenOrdenProducto = idenOrdenProducto;
    }
    public Entregacosto getEntregacosto() {
        return this.entregacosto;
    }
    
    public void setEntregacosto(Entregacosto entregacosto) {
        this.entregacosto = entregacosto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getIdenProdOrdenProducto() {
        return this.idenProdOrdenProducto;
    }
    
    public void setIdenProdOrdenProducto(int idenProdOrdenProducto) {
        this.idenProdOrdenProducto = idenProdOrdenProducto;
    }
    public Date getFechOrdenProducto() {
        return this.fechOrdenProducto;
    }
    
    public void setFechOrdenProducto(Date fechOrdenProducto) {
        this.fechOrdenProducto = fechOrdenProducto;
    }
    public int getCantOrdenProducto() {
        return this.cantOrdenProducto;
    }
    
    public void setCantOrdenProducto(int cantOrdenProducto) {
        this.cantOrdenProducto = cantOrdenProducto;
    }
    public double getPrecOrdenProducto() {
        return this.precOrdenProducto;
    }
    
    public void setPrecOrdenProducto(double precOrdenProducto) {
        this.precOrdenProducto = precOrdenProducto;
    }
    public String getStatusOrdenProducto() {
        return this.statusOrdenProducto;
    }
    
    public void setStatusOrdenProducto(String statusOrdenProducto) {
        this.statusOrdenProducto = statusOrdenProducto;
    }
    public Set getOrdenproductodetalles() {
        return this.ordenproductodetalles;
    }
    
    public void setOrdenproductodetalles(Set ordenproductodetalles) {
        this.ordenproductodetalles = ordenproductodetalles;
    }




}


