package com.edu.unbosque.tiendaonline.entidad;
// Generated 24/11/2015 08:30:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idenUsuario;
     private Rol rol;
     private String nombUsuario;
     private String passUsuario;
     private String emaiUsuario;
     private Date regUsuario;
     private String contaUsuario;
     private Set ordenproductos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Rol rol, String nombUsuario, String passUsuario, String emaiUsuario, Date regUsuario, String contaUsuario) {
        this.rol = rol;
        this.nombUsuario = nombUsuario;
        this.passUsuario = passUsuario;
        this.emaiUsuario = emaiUsuario;
        this.regUsuario = regUsuario;
        this.contaUsuario = contaUsuario;
    }
    public Usuario(Rol rol, String nombUsuario, String passUsuario, String emaiUsuario, Date regUsuario, String contaUsuario, Set ordenproductos) {
       this.rol = rol;
       this.nombUsuario = nombUsuario;
       this.passUsuario = passUsuario;
       this.emaiUsuario = emaiUsuario;
       this.regUsuario = regUsuario;
       this.contaUsuario = contaUsuario;
       this.ordenproductos = ordenproductos;
    }
   
    public Integer getIdenUsuario() {
        return this.idenUsuario;
    }
    
    public void setIdenUsuario(Integer idenUsuario) {
        this.idenUsuario = idenUsuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getNombUsuario() {
        return this.nombUsuario;
    }
    
    public void setNombUsuario(String nombUsuario) {
        this.nombUsuario = nombUsuario;
    }
    public String getPassUsuario() {
        return this.passUsuario;
    }
    
    public void setPassUsuario(String passUsuario) {
        this.passUsuario = passUsuario;
    }
    public String getEmaiUsuario() {
        return this.emaiUsuario;
    }
    
    public void setEmaiUsuario(String emaiUsuario) {
        this.emaiUsuario = emaiUsuario;
    }
    public Date getRegUsuario() {
        return this.regUsuario;
    }
    
    public void setRegUsuario(Date regUsuario) {
        this.regUsuario = regUsuario;
    }
    public String getContaUsuario() {
        return this.contaUsuario;
    }
    
    public void setContaUsuario(String contaUsuario) {
        this.contaUsuario = contaUsuario;
    }
    public Set getOrdenproductos() {
        return this.ordenproductos;
    }
    
    public void setOrdenproductos(Set ordenproductos) {
        this.ordenproductos = ordenproductos;
    }




}


